site_name: iPhone Documentation

# theme:
#   name: material
#   language: zh
#   features:
#     - navigation.instant
#     - navigation.tracking
#     - navigation.tabs
#     - navigation.top

nav:
  - 中文文档:
    - 产品介绍: zh/index.md
  - English Docs:
    - Product Introduction: en/index.md

extra:
  alternate:
    - name: 中文
      link: /zh/
      lang: zh
    - name: English
      link: /en/
      lang: en